// app/layout.tsx

/* RootLayout は「殻」に徹する */
import type { Metadata } from "next";
import { notoSansJp } from '@/app/theme/fonts'
import "./globals.css";

export const metadata: Metadata = {
  title: "Apline",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" className={notoSansJp.variable} suppressHydrationWarning>
      {/**ServerとClientでThemeが違う部分を吸収 */}
      <body>{children}</body>
    </html>
  );
}
